import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sileo';

const interFont = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interFont.variable} h-max antialiased`}>
      <body className="w-full" data-theme="fantasy">
        <Toaster
          position="top-right"
          options={{
            fill: 'black',
            styles: {
              description: 'text-white!',
              badge: 'bg-white/10!',
              button: 'bg-white/10! hover:bg-white/15!',
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
